---
- hosts: all
  become: yes
  
  tasks:
    - name: Atualiza o cache do apt
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags:
        - packages

    - name: Instala o Nginx
      apt:
        name: nginx
        state: present
      tags:
        - packages

    - name: Remove página padrão do Nginx
      file:
        path: /var/www/html/index.nginx-debian.html
        state: absent
      tags:
        - setup

    - name: Copia TODO o conteúdo web para o diretório do Nginx
      ansible.builtin.copy:
        src: files/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
        force: yes
      tags:
        - content

    - name: Habilita e inicia o serviço Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started
      tags:
        - service

    - name: Verifica se o Nginx está rodando
      uri:
        url: http://localhost
        return_content: yes
      register: nginx_status
      failed_when: nginx_status.status != 200
      tags:
        - verification